language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.yml.example config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
